# extract_Z0.py
#
# Purpose: Extract characteristic impedance Z0 from a NeoMoM _Zin.csv
#          sweep of the Burke Fig 2.1.6 open-circuited-line test case,
#          using the same slope method Burke describes (Sec. 2.1):
#
#   Yin = (j/Z0) * tan(2*pi*f*l/c)
#   dYin/df = (2*pi*j*l) / (Z0*c) * sec^2(2*pi*f*l/c)
#   at f0 where l is a multiple of a half wavelength (tan=0, sec^2=1):
#       Z0 = (2*pi*l/c) / (dBin/df)
#
# dBin/df is estimated by linear regression of Bin against f (in Hz)
# across the narrow frequency window generated by gen_burke_case.py.
#
# Usage:
#   python3 extract_Z0.py <s_over_d> <path_to_Zin.csv>

import sys
import os
import numpy as np

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'neomom_Zin', 'src'))
from Zin_reader import read_Zin_file

C_LIGHT = 299792458.0
L = 5.0
A_RAD = 0.001
D = 2.0 * A_RAD
MU0 = 4.0 * np.pi * 1e-7
ETA0 = MU0 * C_LIGHT


def ideal_Z0(s_over_d):
    return (ETA0 / np.pi) * np.arccosh(s_over_d)


def extract_Z0(csv_path):
    meta, data = read_Zin_file(csv_path)
    f_hz = data['freq_mhz'] * 1.0e6
    Bin = data['Bin']

    # Linear regression: Bin = m*f_hz + b -> dBin/df = m
    m, b = np.polyfit(f_hz, Bin, 1)

    Z0 = (2.0 * np.pi * L / C_LIGHT) / m
    return Z0, m


def main():
    if len(sys.argv) != 3:
        print('Usage: python3 extract_Z0.py <s_over_d> <path_to_Zin.csv>')
        sys.exit(1)
    s_over_d = float(sys.argv[1])
    csv_path = sys.argv[2]

    Z0_neomom, slope = extract_Z0(csv_path)
    Z0_ideal = ideal_Z0(s_over_d)

    print(f's/d = {s_over_d:g}')
    print(f'  dBin/df (S/Hz) : {slope:.6e}')
    print(f'  Z0 (NeoMoM)    : {Z0_neomom:.4f} Ohm')
    print(f'  Z0 (ideal)     : {Z0_ideal:.4f} Ohm')
    print(f'  Delta          : {Z0_neomom - Z0_ideal:+.4f} Ohm  '
          f'({100.0*(Z0_neomom-Z0_ideal)/Z0_ideal:+.2f}%)')


if __name__ == '__main__':
    main()
